account_id = "5eb34458406454dda5a7f7b2e6c9a6eb"
name = "lonely-city"
route = "lonely-city.floatingdown.stream/*"
type = "webpack"
workers_dev = false
zone_id = "32dcf0687fc417c71c54b1fd0f196fab"

[site]
bucket = "./dist"
entry-point = "workers-site"
